version: '2'
services:
  hyper-hdr:
    container_name: hyper-hdr
    hostname: hyper-hdr
    image: nocturno/hyper-hdr:latest
    network_mode: host
    devices:
      - /dev/video0:/dev/video0
    environment:
      - TZ=America/New_York

    volumes:
      - /home/pi/containersdata/hyperhdr:/root/.hyperhdr
    restart: unless-stopped
